
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: 
    password: 
    initialization-mode: always
  thymeleaf:
        encoding: UTF-8
  ## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        connection:
          useUnicode: true
          characterEncoding: UTF-8
          charSet: UTF-8
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#Turn Statistics on
#spring.jpa.properties.hibernate.generate_statistics=true
logging:
  level:
    org.hibernate.stat: debug

security:
  oauth2:
    client:
      clientId:
      clientSecret: 
      accessTokenUri:  https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri:  https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri:  https://www.googleapis.com/userinfo/v2/me

server:
  port: 8181

spring.main.allow-bean-definition-overriding: true
